# Generated by Django 6.0.7 on 2026-07-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='学年（医学部は1〜6年）', null=True),
        ),
    ]
