# Generated by Django 6.0.7 on 2026-07-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="学年（医学部は1〜6年）", null=True
                    ),
                ),
                ("student_verified", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("moderator", "モデレーター"),
                            ("admin", "管理者"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="accounts.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロフィール",
                "verbose_name_plural": "プロフィール",
            },
        ),
    ]
