# Generated by Django 6.0.7 on 2026-07-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "preferred_hour",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="通知を送る時刻（0〜23, ユーザーのタイムゾーン基準）",
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Tokyo", max_length=50)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知設定",
                "verbose_name_plural": "通知設定",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True)),
                (
                    "keys",
                    models.JSONField(help_text='{"p256dh": "...", "auth": "..."}'),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push購読",
                "verbose_name_plural": "Push購読",
            },
        ),
    ]
