# Generated by Django 6.0.7 on 2026-07-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notificationpreference_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="バケット内のオブジェクトパス", max_length=500
                    ),
                ),
                ("image_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "アップロード待ち"),
                            ("pending", "審査待ち"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_verifications",
                        to="accounts.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_student_verifications",
                        to="accounts.profile",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        help_text="申請時に本人が選択。承認時に Profile.university に確定される",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生証審査",
                "verbose_name_plural": "学生証審査",
            },
        ),
    ]
