# Generated by Django 6.0.7 on 2026-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_studentverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="ranked_matches",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ポイントが確定した対戦・模試の回数（ランク算出の母集団判定に使う）",
            ),
        ),
    ]
