# Generated by Django 6.0.7 on 2026-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_is_ai_profile_points_profile_ranked_matches"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exam_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "学年に合わせる"),
                    ("CBT", "CBT"),
                    ("KOKUSHI", "医師国家試験"),
                ],
                default="",
                help_text="演習・模試の既定の試験種別。未選択なら学年から決める。",
                max_length=10,
            ),
        ),
    ]
