# Generated by Django 6.0.7 on 2026-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_university_name_kana"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "削除済みアカウント",
                "verbose_name_plural": "削除済みアカウント",
            },
        ),
    ]
