-- habits.0001_initial（1日の目標・学習リマインドの送信記録）を本番に当てる。
-- 何度流しても結果は同じ。
--
-- **デプロイ（PR のマージ）の前に流すこと。** 表が無いまま新しいコードが
-- 動くと、ホームの目標カードと設定画面が 500 になる（解答そのものは止まらない
-- ように作ってあるが、目標が出ない）。先に流しても今のコードは表を使わない
-- ので害はない。
--
-- 中身は manage.py sqlmigrate habits 0001 と同じ。外部キーは CREATE TABLE の
-- 中に書き（名前は Django が付けるものと同じ）、2回目以降は丸ごと飛ばす。
-- django_migrations にも記録するので、あとで manage.py migrate を通しても
-- 二重に作ろうとしない。
BEGIN;

CREATE TABLE IF NOT EXISTS "habits_dailygoal" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "questions_per_day" smallint NOT NULL CHECK ("questions_per_day" >= 0),
    "effective_from" date NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "profile_id" uuid NOT NULL
        CONSTRAINT "habits_dailygoal_profile_id_f81a78d5_fk_accounts_profile_id"
        REFERENCES "accounts_profile" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "habits_goal_one_per_day" UNIQUE ("profile_id", "effective_from")
);
CREATE INDEX IF NOT EXISTS "habits_dailygoal_profile_id_f81a78d5"
    ON "habits_dailygoal" ("profile_id");

CREATE TABLE IF NOT EXISTS "habits_reminderlog" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "sent_on" date NOT NULL,
    "kind" varchar(10) NOT NULL,
    "template" varchar(20) NOT NULL,
    "sent_at" timestamp with time zone NOT NULL,
    "profile_id" uuid NOT NULL
        CONSTRAINT "habits_reminderlog_profile_id_6d7acd39_fk_accounts_profile_id"
        REFERENCES "accounts_profile" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "habits_reminder_once_a_day" UNIQUE ("profile_id", "sent_on", "kind")
);
CREATE INDEX IF NOT EXISTS "habits_reminderlog_profile_id_6d7acd39"
    ON "habits_reminderlog" ("profile_id");

-- supabase/migrations/20260723000100_rls_lockdown.sql と同じ方針で RLS を
-- 有効にする。ポリシーを作らないので Data API（anon キー）からは全部拒否に
-- なる（Django は所有者 postgres で繋ぐので影響しない）。
ALTER TABLE "habits_dailygoal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "habits_reminderlog" ENABLE ROW LEVEL SECURITY;

INSERT INTO django_migrations (app, name, applied)
SELECT 'habits', '0001_initial', NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations WHERE app = 'habits' AND name = '0001_initial'
);

COMMIT;
