import csv
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from quiz.models import CBTBlueprint

EXPECTED_COLUMNS = {
    "code",
    "section",
    "area",
    "area_title",
    "subsection_title",
    "objective_text",
    "depth",
    "class_group",
    "disease_names",
}


class Command(BaseCommand):
    help = (
        "Import the CBT 出題基準 index from data/cbt_blueprint.csv "
        "(generated by scripts/extract_blueprint.py). objective_text is kept "
        "for generation prompts only and is never exposed via the API."
    )

    def add_arguments(self, parser):
        parser.add_argument("--file", required=True, help="Path to cbt_blueprint.csv")

    def handle(self, *args, **options):
        path = Path(options["file"])
        if not path.exists():
            raise CommandError(f"File not found: {path}")

        created, updated = 0, 0
        with path.open(encoding="utf-8") as f:
            reader = csv.DictReader(f)
            missing = EXPECTED_COLUMNS - set(reader.fieldnames or [])
            if missing:
                raise CommandError(f"Missing columns: {sorted(missing)}")
            for row in reader:
                diseases = [d.strip() for d in (row["disease_names"] or "").split("|") if d.strip()]
                _, was_created = CBTBlueprint.objects.update_or_create(
                    code=row["code"].strip(),
                    defaults=dict(
                        section=row["section"].strip(),
                        area=row["area"].strip(),
                        area_title=row["area_title"].strip(),
                        subsection_title=row["subsection_title"].strip(),
                        objective_text=row["objective_text"].strip(),
                        depth=row["depth"].strip(),
                        class_group=row["class_group"].strip(),
                        disease_names=diseases,
                    ),
                )
                created += int(was_created)
                updated += int(not was_created)

        self.stdout.write(
            self.style.SUCCESS(
                f"Blueprint import done: {created} created, {updated} updated "
                f"(total: {CBTBlueprint.objects.count()})."
            )
        )
