from django.core.management.base import BaseCommand

from quiz.models import Question

# Original sample questions (not reproductions of real CBT/国試 exam content)
# covering the remaining category list requested for the home screen.
EXTRA_QUESTIONS = [
    # 基礎医学
    dict(category="基礎医学", exam_type="CBT", difficulty=1,
         question_text="ヒトの体細胞の染色体数として正しいのはどれか。",
         choices=[{"key": "A", "text": "44"}, {"key": "B", "text": "45"}, {"key": "C", "text": "46"}, {"key": "D", "text": "47"}, {"key": "E", "text": "48"}],
         correct_choice_key="C",
         explanation="ヒトの体細胞は44本の常染色体と2本の性染色体、計46本(23対)の染色体を持つ。"),
    dict(category="基礎医学", exam_type="CBT", difficulty=2,
         question_text="DNAの複製に伴い岡崎フラグメントが生じる鎖はどれか。",
         choices=[{"key": "A", "text": "リーディング鎖"}, {"key": "B", "text": "ラギング鎖"}, {"key": "C", "text": "mRNA"}, {"key": "D", "text": "tRNA"}],
         correct_choice_key="B",
         explanation="ラギング鎖は5'→3'方向にしか合成できないDNAポリメラーゼの制約により不連続に合成され、岡崎フラグメントを形成する。"),
    dict(category="基礎医学", exam_type="CBT", difficulty=2,
         question_text="酵素反応の最大反応速度(Vmax)を低下させるがKm値は変化させない阻害様式はどれか。",
         choices=[{"key": "A", "text": "競合阻害"}, {"key": "B", "text": "非競合阻害"}, {"key": "C", "text": "不競合阻害"}, {"key": "D", "text": "無阻害"}],
         correct_choice_key="B",
         explanation="非競合阻害では阻害薬が基質結合部位以外に結合しVmaxを低下させるが、Kmは変化しない。"),
    dict(category="基礎医学", exam_type="KOKUSHI", difficulty=3,
         question_text="細胞小器官のうちATP産生の主座はどれか。",
         choices=[{"key": "A", "text": "ゴルジ体"}, {"key": "B", "text": "リソソーム"}, {"key": "C", "text": "ミトコンドリア"}, {"key": "D", "text": "粗面小胞体"}],
         correct_choice_key="C",
         explanation="ミトコンドリアは酸化的リン酸化によりATPを産生する細胞のエネルギー産生中枢である。"),
    dict(category="基礎医学", exam_type="KOKUSHI", difficulty=3,
         question_text="X連鎖劣性(伴性劣性)遺伝形式をとる代表的疾患はどれか。",
         choices=[{"key": "A", "text": "マルファン症候群"}, {"key": "B", "text": "血友病A"}, {"key": "C", "text": "軟骨無形成症"}, {"key": "D", "text": "常染色体優性多発性嚢胞腎"}],
         correct_choice_key="B",
         explanation="血友病Aは第VIII因子遺伝子異常によるX連鎖劣性遺伝疾患であり、主に男性に発症する。"),

    # 公衆衛生
    dict(category="公衆衛生", exam_type="CBT", difficulty=1,
         question_text="ある集団において一定期間内に新たに疾病を発症した者の割合を示す指標はどれか。",
         choices=[{"key": "A", "text": "有病率"}, {"key": "B", "text": "罹患率"}, {"key": "C", "text": "致命率"}, {"key": "D", "text": "相対危険度"}],
         correct_choice_key="B",
         explanation="罹患率(発生率)は一定期間内に新規発症した患者数を観察対象人年で除した指標である。"),
    dict(category="公衆衛生", exam_type="CBT", difficulty=2,
         question_text="スクリーニング検査において、実際に疾患を有する者を正しく陽性と判定する割合を示す指標はどれか。",
         choices=[{"key": "A", "text": "特異度"}, {"key": "B", "text": "感度"}, {"key": "C", "text": "陽性的中率"}, {"key": "D", "text": "陰性的中率"}],
         correct_choice_key="B",
         explanation="感度は真の陽性者を正しく陽性と判定する割合であり、疾患の見逃しの少なさを表す。"),
    dict(category="公衆衛生", exam_type="CBT", difficulty=1,
         question_text="我が国の予防接種法に基づくA類疾病に分類されるのはどれか。",
         choices=[{"key": "A", "text": "季節性インフルエンザ"}, {"key": "B", "text": "麻疹"}, {"key": "C", "text": "破傷風(任意接種のみ)"}, {"key": "D", "text": "成人用肺炎球菌"}],
         correct_choice_key="B",
         explanation="麻疹は集団予防を目的としたA類疾病に位置づけられ、定期接種が原則勧奨される。"),
    dict(category="公衆衛生", exam_type="KOKUSHI", difficulty=3,
         question_text="要介護認定に基づき介護サービスを給付する制度はどれか。",
         choices=[{"key": "A", "text": "医療保険制度"}, {"key": "B", "text": "介護保険制度"}, {"key": "C", "text": "後期高齢者医療制度"}, {"key": "D", "text": "生活保護制度"}],
         correct_choice_key="B",
         explanation="介護保険制度は市町村が保険者となり、要介護認定に基づき介護サービスを給付する制度である。"),
    dict(category="公衆衛生", exam_type="KOKUSHI", difficulty=2,
         question_text="二次予防に該当する活動はどれか。",
         choices=[{"key": "A", "text": "禁煙指導"}, {"key": "B", "text": "がん検診"}, {"key": "C", "text": "予防接種"}, {"key": "D", "text": "リハビリテーション"}],
         correct_choice_key="B",
         explanation="二次予防は早期発見・早期治療を目的とし、がん検診はその代表例である。"),

    # 臨床医学総論
    dict(category="臨床医学総論", exam_type="CBT", difficulty=1,
         question_text="バイタルサインに含まれないのはどれか。",
         choices=[{"key": "A", "text": "体温"}, {"key": "B", "text": "脈拍"}, {"key": "C", "text": "血糖値"}, {"key": "D", "text": "呼吸数"}, {"key": "E", "text": "血圧"}],
         correct_choice_key="C",
         explanation="バイタルサインは体温・脈拍・呼吸数・血圧(および意識レベル)であり、血糖値は含まれない。"),
    dict(category="臨床医学総論", exam_type="CBT", difficulty=1,
         question_text="成人の正常な安静時心拍数の範囲として適切なのはどれか。",
         choices=[{"key": "A", "text": "30-40/分"}, {"key": "B", "text": "60-100/分"}, {"key": "C", "text": "120-140/分"}, {"key": "D", "text": "150-160/分"}],
         correct_choice_key="B",
         explanation="成人の安静時心拍数は一般に60〜100/分が正常範囲とされる。"),
    dict(category="臨床医学総論", exam_type="CBT", difficulty=2,
         question_text="SOAP形式のカルテ記載における「O」が示す内容はどれか。",
         choices=[{"key": "A", "text": "主観的情報"}, {"key": "B", "text": "客観的所見"}, {"key": "C", "text": "評価"}, {"key": "D", "text": "計画"}],
         correct_choice_key="B",
         explanation="SOAPのOはObjective(客観的所見)を指し、身体所見や検査結果を記載する。"),
    dict(category="臨床医学総論", exam_type="KOKUSHI", difficulty=2,
         question_text="インフォームド・コンセントの説明として適切なのはどれか。",
         choices=[{"key": "A", "text": "医師が一方的に治療方針を決定すること"}, {"key": "B", "text": "患者に十分な説明を行い同意を得ること"}, {"key": "C", "text": "家族のみに説明すること"}, {"key": "D", "text": "緊急時のみ必要な手続き"}],
         correct_choice_key="B",
         explanation="インフォームド・コンセントは患者本人に十分な説明を行い、理解と同意を得た上で医療を行う原則である。"),
    dict(category="臨床医学総論", exam_type="KOKUSHI", difficulty=3,
         question_text="プライマリ・ケアの特徴として適切でないのはどれか。",
         choices=[{"key": "A", "text": "近接性"}, {"key": "B", "text": "包括性"}, {"key": "C", "text": "高度先進医療への特化"}, {"key": "D", "text": "継続性"}],
         correct_choice_key="C",
         explanation="プライマリ・ケアは近接性・包括性・継続性・協調性を特徴とし、高度先進医療への特化はむしろ三次医療機関の役割である。"),

    # 腎臓
    dict(category="腎臓", exam_type="CBT", difficulty=1,
         question_text="糸球体濾過量(GFR)の推算に用いられる血液検査項目はどれか。",
         choices=[{"key": "A", "text": "血清クレアチニン"}, {"key": "B", "text": "血清アルブミン"}, {"key": "C", "text": "血清カリウム"}, {"key": "D", "text": "CRP"}],
         correct_choice_key="A",
         explanation="血清クレアチニン値、年齢、性別からeGFRが推算され、腎機能評価の基本指標となる。"),
    dict(category="腎臓", exam_type="CBT", difficulty=2,
         question_text="ネフローゼ症候群の診断基準に含まれるのはどれか。",
         choices=[{"key": "A", "text": "高度蛋白尿と低アルブミン血症"}, {"key": "B", "text": "血尿のみ"}, {"key": "C", "text": "高血糖"}, {"key": "D", "text": "白血球増多"}],
         correct_choice_key="A",
         explanation="ネフローゼ症候群は高度蛋白尿(3.5g/日以上)、低アルブミン血症、浮腫、脂質異常症を特徴とする。"),
    dict(category="腎臓", exam_type="CBT", difficulty=2,
         question_text="慢性腎臓病(CKD)の重症度分類に用いられる2指標はどれか。",
         choices=[{"key": "A", "text": "GFRと尿蛋白"}, {"key": "B", "text": "血圧と脈拍"}, {"key": "C", "text": "体温と白血球数"}, {"key": "D", "text": "血糖とHbA1c"}],
         correct_choice_key="A",
         explanation="CKDの重症度はGFR区分と尿蛋白(アルブミン尿)区分の組み合わせで評価される。"),
    dict(category="腎臓", exam_type="KOKUSHI", difficulty=3,
         question_text="急性腎障害(AKI)の原因分類に含まれないのはどれか。",
         choices=[{"key": "A", "text": "腎前性"}, {"key": "B", "text": "腎性"}, {"key": "C", "text": "腎後性"}, {"key": "D", "text": "腎外性"}],
         correct_choice_key="D",
         explanation="AKIは腎前性・腎性・腎後性の3つに分類され、「腎外性」という分類名は用いられない。"),
    dict(category="腎臓", exam_type="KOKUSHI", difficulty=3,
         question_text="高カリウム血症の心電図所見として特徴的なのはどれか。",
         choices=[{"key": "A", "text": "テント状T波"}, {"key": "B", "text": "U波の出現"}, {"key": "C", "text": "QT延長"}, {"key": "D", "text": "ST低下"}],
         correct_choice_key="A",
         explanation="高カリウム血症では左右対称性に尖鋭化したテント状T波が特徴的な初期変化である。"),

    # 血液
    dict(category="血液", exam_type="CBT", difficulty=1,
         question_text="鉄欠乏性貧血で特徴的な赤血球指数の変化はどれか。",
         choices=[{"key": "A", "text": "小球性低色素性"}, {"key": "B", "text": "大球性正色素性"}, {"key": "C", "text": "正球性正色素性"}, {"key": "D", "text": "小球性正色素性"}],
         correct_choice_key="A",
         explanation="鉄欠乏性貧血ではヘモグロビン合成障害によりMCV・MCHCがともに低下する小球性低色素性貧血を呈する。"),
    dict(category="血液", exam_type="CBT", difficulty=2,
         question_text="ビタミンB12欠乏で生じる貧血の分類はどれか。",
         choices=[{"key": "A", "text": "溶血性貧血"}, {"key": "B", "text": "大球性貧血"}, {"key": "C", "text": "小球性貧血"}, {"key": "D", "text": "再生不良性貧血"}],
         correct_choice_key="B",
         explanation="ビタミンB12欠乏はDNA合成障害を介し大球性貧血(巨赤芽球性貧血)をきたす。"),
    dict(category="血液", exam_type="CBT", difficulty=2,
         question_text="血友病で延長する凝固検査項目はどれか。",
         choices=[{"key": "A", "text": "PT"}, {"key": "B", "text": "APTT"}, {"key": "C", "text": "出血時間"}, {"key": "D", "text": "血小板数"}],
         correct_choice_key="B",
         explanation="血友病は内因系凝固因子(第VIII・IX因子)欠乏によりAPTTが延長する。"),
    dict(category="血液", exam_type="KOKUSHI", difficulty=3,
         question_text="播種性血管内凝固症候群(DIC)でみられる所見はどれか。",
         choices=[{"key": "A", "text": "血小板増多とFDP低下"}, {"key": "B", "text": "血小板減少とFDP上昇"}, {"key": "C", "text": "PT短縮"}, {"key": "D", "text": "フィブリノゲン上昇"}],
         correct_choice_key="B",
         explanation="DICでは全身性の凝固活性化により血小板・フィブリノゲンが消費され減少し、FDP/D-dimerは上昇する。"),
    dict(category="血液", exam_type="KOKUSHI", difficulty=3,
         question_text="慢性骨髄性白血病(CML)に特徴的な染色体異常はどれか。",
         choices=[{"key": "A", "text": "フィラデルフィア染色体"}, {"key": "B", "text": "21トリソミー"}, {"key": "C", "text": "5番染色体長腕欠失"}, {"key": "D", "text": "モノソミー7"}],
         correct_choice_key="A",
         explanation="CMLはt(9;22)転座によるフィラデルフィア染色体(BCR-ABL融合遺伝子)を特徴とする。"),

    # 免疫
    dict(category="免疫", exam_type="CBT", difficulty=1,
         question_text="即時型(I型)アレルギーに関与する主な抗体はどれか。",
         choices=[{"key": "A", "text": "IgG"}, {"key": "B", "text": "IgA"}, {"key": "C", "text": "IgE"}, {"key": "D", "text": "IgM"}],
         correct_choice_key="C",
         explanation="I型アレルギーは肥満細胞・好塩基球上のIgEを介した即時型過敏反応である。"),
    dict(category="免疫", exam_type="CBT", difficulty=2,
         question_text="全身性エリテマトーデス(SLE)の診断に有用な自己抗体はどれか。",
         choices=[{"key": "A", "text": "抗核抗体"}, {"key": "B", "text": "抗アセチルコリン受容体抗体"}, {"key": "C", "text": "抗TSH受容体抗体"}, {"key": "D", "text": "抗ミトコンドリア抗体"}],
         correct_choice_key="A",
         explanation="抗核抗体はSLEでほぼ全例陽性となる感度の高いスクリーニング抗体である。"),
    dict(category="免疫", exam_type="CBT", difficulty=3,
         question_text="移植免疫における拒絶反応のうち、数分〜数時間以内に生じるのはどれか。",
         choices=[{"key": "A", "text": "超急性拒絶"}, {"key": "B", "text": "急性拒絶"}, {"key": "C", "text": "慢性拒絶"}, {"key": "D", "text": "遅発性拒絶"}],
         correct_choice_key="A",
         explanation="超急性拒絶は既存の抗ドナー抗体により補体が活性化し、移植直後から数時間以内に生じる。"),
    dict(category="免疫", exam_type="KOKUSHI", difficulty=3,
         question_text="補体の活性化経路に含まれないのはどれか。",
         choices=[{"key": "A", "text": "古典経路"}, {"key": "B", "text": "第二経路(副経路)"}, {"key": "C", "text": "レクチン経路"}, {"key": "D", "text": "酵素経路"}],
         correct_choice_key="D",
         explanation="補体活性化には古典経路・第二経路(副経路)・レクチン経路の3経路があり、「酵素経路」という名称は用いられない。"),
    dict(category="免疫", exam_type="KOKUSHI", difficulty=3,
         question_text="液性免疫不全に分類される一次免疫不全症はどれか。",
         choices=[{"key": "A", "text": "慢性肉芽腫症"}, {"key": "B", "text": "ブルトン型無ガンマグロブリン血症"}, {"key": "C", "text": "DiGeorge症候群"}, {"key": "D", "text": "重症複合免疫不全症"}],
         correct_choice_key="B",
         explanation="ブルトン型無ガンマグロブリン血症はBTK遺伝子異常によるB細胞成熟障害で、液性免疫不全を呈する。"),

    # 感染症
    dict(category="感染症", exam_type="CBT", difficulty=1,
         question_text="グラム陽性球菌に分類される代表的な起因菌はどれか。",
         choices=[{"key": "A", "text": "大腸菌"}, {"key": "B", "text": "黄色ブドウ球菌"}, {"key": "C", "text": "緑膿菌"}, {"key": "D", "text": "クラミジア"}],
         correct_choice_key="B",
         explanation="黄色ブドウ球菌はグラム染色で陽性に染まる球菌であり、皮膚軟部組織感染症の代表的起因菌である。"),
    dict(category="感染症", exam_type="CBT", difficulty=2,
         question_text="経気道感染(空気感染)で伝播する代表的疾患はどれか。",
         choices=[{"key": "A", "text": "麻疹"}, {"key": "B", "text": "B型肝炎"}, {"key": "C", "text": "マラリア"}, {"key": "D", "text": "破傷風"}],
         correct_choice_key="A",
         explanation="麻疹ウイルスは空気感染(飛沫核感染)で伝播し、感染力が極めて強い。"),
    dict(category="感染症", exam_type="CBT", difficulty=2,
         question_text="抗菌薬のうち細胞壁合成を阻害するのはどれか。",
         choices=[{"key": "A", "text": "マクロライド系"}, {"key": "B", "text": "βラクタム系"}, {"key": "C", "text": "アミノグリコシド系"}, {"key": "D", "text": "ニューキノロン系"}],
         correct_choice_key="B",
         explanation="βラクタム系抗菌薬(ペニシリン系・セフェム系)は細菌の細胞壁ペプチドグリカン合成を阻害する。"),
    dict(category="感染症", exam_type="KOKUSHI", difficulty=2,
         question_text="針刺し事故で最も感染リスクが高いとされるウイルスはどれか。",
         choices=[{"key": "A", "text": "HIV"}, {"key": "B", "text": "HBV"}, {"key": "C", "text": "HCV"}, {"key": "D", "text": "HTLV-1"}],
         correct_choice_key="B",
         explanation="針刺し事故における感染リスクはHBVが最も高く、次いでHCV、HIVの順とされる。"),
    dict(category="感染症", exam_type="KOKUSHI", difficulty=3,
         question_text="敗血症性ショックの初期対応として推奨されるのはどれか。",
         choices=[{"key": "A", "text": "早期の広域抗菌薬投与と輸液蘇生"}, {"key": "B", "text": "ただちに利尿薬投与"}, {"key": "C", "text": "絶食のみで経過観察"}, {"key": "D", "text": "血液培養結果が出るまで抗菌薬を待つ"}],
         correct_choice_key="A",
         explanation="敗血症性ショックでは早期認識のもと迅速な輸液蘇生と広域抗菌薬の早期投与が予後改善に直結する。"),

    # 中毒・環境異常症
    dict(category="中毒・環境異常症", exam_type="CBT", difficulty=1,
         question_text="一酸化炭素中毒の治療として最も重要なのはどれか。",
         choices=[{"key": "A", "text": "高濃度酸素投与"}, {"key": "B", "text": "利尿薬投与"}, {"key": "C", "text": "抗菌薬投与"}, {"key": "D", "text": "ステロイド投与"}],
         correct_choice_key="A",
         explanation="COはヘモグロビンとの親和性が酸素の約200倍高く、高濃度酸素投与によりCOHbの解離を促進する。"),
    dict(category="中毒・環境異常症", exam_type="CBT", difficulty=2,
         question_text="有機リン中毒の解毒薬として用いられるのはどれか。",
         choices=[{"key": "A", "text": "アトロピン"}, {"key": "B", "text": "ナロキソン"}, {"key": "C", "text": "フルマゼニル"}, {"key": "D", "text": "グルカゴン"}],
         correct_choice_key="A",
         explanation="有機リン中毒はアセチルコリンエステラーゼ阻害によりコリン作動性症状を呈し、抗コリン薬アトロピンが解毒に用いられる。"),
    dict(category="中毒・環境異常症", exam_type="CBT", difficulty=2,
         question_text="熱中症の重症度分類で意識障害を伴う場合に該当する病型はどれか。",
         choices=[{"key": "A", "text": "熱失神"}, {"key": "B", "text": "熱痙攣"}, {"key": "C", "text": "熱疲労"}, {"key": "D", "text": "熱射病"}],
         correct_choice_key="D",
         explanation="熱射病は中枢神経障害(意識障害)を伴う最重症型であり、緊急の全身冷却が必要となる。"),
    dict(category="中毒・環境異常症", exam_type="KOKUSHI", difficulty=3,
         question_text="低体温症の初期対応として適切なのはどれか。",
         choices=[{"key": "A", "text": "四肢末梢から急速に温める"}, {"key": "B", "text": "中心部から緩徐に加温する"}, {"key": "C", "text": "冷水浴を行う"}, {"key": "D", "text": "積極的に運動させる"}],
         correct_choice_key="B",
         explanation="低体温症では四肢末梢からの急激な加温はafterdropを招くため、中心部優先の緩徐な加温が推奨される。"),
    dict(category="中毒・環境異常症", exam_type="KOKUSHI", difficulty=3,
         question_text="アセトアミノフェン中毒の特異的解毒薬はどれか。",
         choices=[{"key": "A", "text": "N-アセチルシステイン"}, {"key": "B", "text": "ジメルカプロール"}, {"key": "C", "text": "デフェロキサミン"}, {"key": "D", "text": "フォミピゾール"}],
         correct_choice_key="A",
         explanation="N-アセチルシステインはグルタチオン補充により肝毒性代謝物を無毒化し、アセトアミノフェン中毒の特異的解毒薬となる。"),

    # 救急
    dict(category="救急", exam_type="CBT", difficulty=1,
         question_text="成人の一次救命処置(BLS)における胸骨圧迫の深さの目安はどれか。",
         choices=[{"key": "A", "text": "約1cm"}, {"key": "B", "text": "約2cm"}, {"key": "C", "text": "約5cm"}, {"key": "D", "text": "約10cm"}],
         correct_choice_key="C",
         explanation="成人の胸骨圧迫は約5cm(6cmを超えない)の深さで、100〜120回/分のテンポで行うことが推奨される。"),
    dict(category="救急", exam_type="CBT", difficulty=2,
         question_text="気道異物による窒息が疑われる意識のある傷病者への対応として適切なのはどれか。",
         choices=[{"key": "A", "text": "背部叩打法や腹部突き上げ法"}, {"key": "B", "text": "ただちに人工呼吸"}, {"key": "C", "text": "経過観察のみ"}, {"key": "D", "text": "仰臥位に固定するのみ"}],
         correct_choice_key="A",
         explanation="意識のある窒息傷病者には背部叩打法・腹部突き上げ法(ハイムリック法)による異物除去を試みる。"),
    dict(category="救急", exam_type="CBT", difficulty=2,
         question_text="トリアージにおいて最優先(赤色)で治療を要するのはどれか。",
         choices=[{"key": "A", "text": "歩行可能な軽症者"}, {"key": "B", "text": "気道確保が必要な重症者"}, {"key": "C", "text": "死亡が確認された者"}, {"key": "D", "text": "軽度の擦過傷のみの者"}],
         correct_choice_key="B",
         explanation="トリアージの赤(最優先)は生命危機があり直ちに処置すれば救命可能な重症者に割り当てられる。"),
    dict(category="救急", exam_type="KOKUSHI", difficulty=3,
         question_text="ショックの分類のうち、心タンポナーデが原因となるのはどれか。",
         choices=[{"key": "A", "text": "循環血液量減少性ショック"}, {"key": "B", "text": "心原性ショック"}, {"key": "C", "text": "閉塞性ショック"}, {"key": "D", "text": "血液分布異常性ショック"}],
         correct_choice_key="C",
         explanation="心タンポナーデや緊張性気胸は心臓への血流を物理的に妨げる閉塞性ショックに分類される。"),
    dict(category="救急", exam_type="KOKUSHI", difficulty=2,
         question_text="グラスゴー・コーマ・スケール(GCS)で評価しない項目はどれか。",
         choices=[{"key": "A", "text": "開眼"}, {"key": "B", "text": "言語反応"}, {"key": "C", "text": "運動反応"}, {"key": "D", "text": "瞳孔径"}],
         correct_choice_key="D",
         explanation="GCSは開眼(E)・言語反応(V)・運動反応(M)の3要素で評価し、瞳孔径は含まれない。"),

    # 小児
    dict(category="小児", exam_type="CBT", difficulty=1,
         question_text="生後の原始反射のうち、生後4〜6か月頃に消失するのが正常とされるのはどれか。",
         choices=[{"key": "A", "text": "モロー反射"}, {"key": "B", "text": "膝蓋腱反射"}, {"key": "C", "text": "対光反射"}, {"key": "D", "text": "咳嗽反射"}],
         correct_choice_key="A",
         explanation="モロー反射は原始反射の一つで、通常生後4〜6か月頃までに消失する。残存は中枢神経系異常を示唆する。"),
    dict(category="小児", exam_type="CBT", difficulty=2,
         question_text="川崎病の主要症状に含まれないのはどれか。",
         choices=[{"key": "A", "text": "5日以上続く発熱"}, {"key": "B", "text": "イチゴ舌"}, {"key": "C", "text": "四肢末端の変化"}, {"key": "D", "text": "関節可動域の著明な制限"}],
         correct_choice_key="D",
         explanation="川崎病の主要症状は発熱、両側眼球結膜充血、口唇・口腔所見(イチゴ舌等)、発疹、頸部リンパ節腫脹、四肢末端の変化であり、関節可動域制限は主要症状に含まれない。"),
    dict(category="小児", exam_type="CBT", difficulty=2,
         question_text="母乳栄養児に発症しやすい欠乏症はどれか。",
         choices=[{"key": "A", "text": "ビタミンK欠乏症"}, {"key": "B", "text": "ビタミンA過剰症"}, {"key": "C", "text": "鉄過剰症"}, {"key": "D", "text": "カルシウム過剰症"}],
         correct_choice_key="A",
         explanation="母乳中のビタミンK含有量は少なく、母乳栄養児は新生児メレナや乳児期頭蓋内出血のリスクとなるビタミンK欠乏をきたしやすい。"),
    dict(category="小児", exam_type="KOKUSHI", difficulty=2,
         question_text="標準的な予防接種スケジュールにおいて出生直後から開始されるのはどれか。",
         choices=[{"key": "A", "text": "BCG"}, {"key": "B", "text": "B型肝炎ワクチン"}, {"key": "C", "text": "麻疹風疹混合ワクチン"}, {"key": "D", "text": "日本脳炎ワクチン"}],
         correct_choice_key="B",
         explanation="B型肝炎ワクチンは母子感染予防の観点から出生直後からの接種スケジュールが組まれている。"),
    dict(category="小児", exam_type="KOKUSHI", difficulty=3,
         question_text="標準的な発達段階として、通常生後9〜10か月頃に獲得される運動機能はどれか。",
         choices=[{"key": "A", "text": "首がすわる"}, {"key": "B", "text": "寝返り"}, {"key": "C", "text": "つかまり立ち"}, {"key": "D", "text": "独歩"}],
         correct_choice_key="C",
         explanation="標準的な運動発達では首すわり(生後3-4か月)、寝返り(5-6か月)、つかまり立ち(9-10か月)、独歩(12-18か月)の順に獲得される。"),

    # 産科
    dict(category="産科", exam_type="CBT", difficulty=1,
         question_text="妊娠週数の数え方として正しいのはどれか。",
         choices=[{"key": "A", "text": "最終月経初日を0週0日とする"}, {"key": "B", "text": "受精日を0週0日とする"}, {"key": "C", "text": "着床日を1週0日とする"}, {"key": "D", "text": "排卵日を2週0日とする"}],
         correct_choice_key="A",
         explanation="妊娠週数は最終月経初日を0週0日として起算する(受精は通常2週頃に相当)。"),
    dict(category="産科", exam_type="CBT", difficulty=2,
         question_text="妊娠高血圧症候群の定義に用いられる血圧の基準はどれか。",
         choices=[{"key": "A", "text": "収縮期100mmHg以上"}, {"key": "B", "text": "収縮期140mmHg以上または拡張期90mmHg以上"}, {"key": "C", "text": "収縮期160mmHg以上のみ"}, {"key": "D", "text": "拡張期70mmHg以上"}],
         correct_choice_key="B",
         explanation="妊娠高血圧症候群は妊娠20週以降に収縮期血圧140mmHg以上または拡張期血圧90mmHg以上を認める場合と定義される。"),
    dict(category="産科", exam_type="CBT", difficulty=2,
         question_text="前置胎盤の典型的な臨床症状はどれか。",
         choices=[{"key": "A", "text": "無痛性性器出血"}, {"key": "B", "text": "持続する下腹部痛のみ"}, {"key": "C", "text": "発熱"}, {"key": "D", "text": "排尿障害"}],
         correct_choice_key="A",
         explanation="前置胎盤は妊娠後期に突然の無痛性性器出血をきたすことが典型的である。"),
    dict(category="産科", exam_type="KOKUSHI", difficulty=3,
         question_text="分娩第2期に該当するのはどれか。",
         choices=[{"key": "A", "text": "陣痛開始から子宮口全開大まで"}, {"key": "B", "text": "子宮口全開大から児娩出まで"}, {"key": "C", "text": "児娩出から胎盤娩出まで"}, {"key": "D", "text": "胎盤娩出後2時間の観察期間"}],
         correct_choice_key="B",
         explanation="分娩第2期は子宮口全開大から胎児娩出までの期間を指す。"),
    dict(category="産科", exam_type="KOKUSHI", difficulty=2,
         question_text="妊娠糖尿病のスクリーニングに用いられる検査はどれか。",
         choices=[{"key": "A", "text": "75gOGTT"}, {"key": "B", "text": "HbA1c単独"}, {"key": "C", "text": "尿蛋白定量"}, {"key": "D", "text": "血算"}],
         correct_choice_key="A",
         explanation="妊娠糖尿病のスクリーニング・診断には75g経口ブドウ糖負荷試験(OGTT)が広く用いられる。"),

    # 婦人科
    dict(category="婦人科", exam_type="CBT", difficulty=1,
         question_text="子宮頸癌の主な原因となるウイルスはどれか。",
         choices=[{"key": "A", "text": "HSV"}, {"key": "B", "text": "HPV"}, {"key": "C", "text": "EBV"}, {"key": "D", "text": "HBV"}],
         correct_choice_key="B",
         explanation="子宮頸癌のほとんどはヒトパピローマウイルス(HPV)の持続感染に起因する。"),
    dict(category="婦人科", exam_type="CBT", difficulty=2,
         question_text="月経周期における排卵の指標となるホルモン変化はどれか。",
         choices=[{"key": "A", "text": "LHサージ"}, {"key": "B", "text": "プロラクチンの持続低下"}, {"key": "C", "text": "hCGの上昇"}, {"key": "D", "text": "TSHの上昇"}],
         correct_choice_key="A",
         explanation="排卵は下垂体からのLHサージにより誘発される。"),
    dict(category="婦人科", exam_type="CBT", difficulty=2,
         question_text="多嚢胞性卵巣症候群(PCOS)の特徴として適切なのはどれか。",
         choices=[{"key": "A", "text": "高LH/FSH比とインスリン抵抗性"}, {"key": "B", "text": "著明な高FSH血症"}, {"key": "C", "text": "早発閉経"}, {"key": "D", "text": "子宮内膜の萎縮"}],
         correct_choice_key="A",
         explanation="PCOSはLH/FSH比の上昇、インスリン抵抗性、多嚢胞性卵巣、無排卵を特徴とする内分泌疾患である。"),
    dict(category="婦人科", exam_type="KOKUSHI", difficulty=2,
         question_text="子宮内膜症の代表的症状はどれか。",
         choices=[{"key": "A", "text": "進行性の月経困難症"}, {"key": "B", "text": "無月経のみ"}, {"key": "C", "text": "発熱"}, {"key": "D", "text": "体重増加"}],
         correct_choice_key="A",
         explanation="子宮内膜症は月経のたびに増悪する進行性の月経困難症や骨盤痛を特徴とする。"),
    dict(category="婦人科", exam_type="KOKUSHI", difficulty=1,
         question_text="乳癌検診に用いられる代表的な画像検査はどれか。",
         choices=[{"key": "A", "text": "マンモグラフィ"}, {"key": "B", "text": "腹部エコー"}, {"key": "C", "text": "骨シンチグラフィ"}, {"key": "D", "text": "胸部単純X線"}],
         correct_choice_key="A",
         explanation="マンモグラフィは乳癌検診における標準的な画像検査であり、微細石灰化の検出に優れる。"),

    # 泌尿器
    dict(category="泌尿器", exam_type="CBT", difficulty=1,
         question_text="前立腺特異抗原(PSA)が上昇する疾患はどれか。",
         choices=[{"key": "A", "text": "前立腺癌"}, {"key": "B", "text": "膀胱炎"}, {"key": "C", "text": "腎結石"}, {"key": "D", "text": "精巣捻転"}],
         correct_choice_key="A",
         explanation="PSAは前立腺癌のスクリーニングに用いられる腫瘍マーカーであり、前立腺肥大症でも軽度上昇しうる。"),
    dict(category="泌尿器", exam_type="CBT", difficulty=2,
         question_text="尿路結石の成分として最も頻度が高いのはどれか。",
         choices=[{"key": "A", "text": "シュウ酸カルシウム結石"}, {"key": "B", "text": "尿酸結石"}, {"key": "C", "text": "シスチン結石"}, {"key": "D", "text": "リン酸アンモニウムマグネシウム結石"}],
         correct_choice_key="A",
         explanation="尿路結石の中で最も頻度が高いのはシュウ酸カルシウムを主成分とする結石である。"),
    dict(category="泌尿器", exam_type="KOKUSHI", difficulty=3,
         question_text="精巣捻転の初期対応として最も重要なのはどれか。",
         choices=[{"key": "A", "text": "緊急手術による整復・固定"}, {"key": "B", "text": "抗菌薬投与のみで経過観察"}, {"key": "C", "text": "冷罨法"}, {"key": "D", "text": "鎮痛薬投与のみで帰宅"}],
         correct_choice_key="A",
         explanation="精巣捻転は発症から6時間以内の緊急手術による整復が精巣温存の鍵となる。"),
    dict(category="泌尿器", exam_type="CBT", difficulty=2,
         question_text="過活動膀胱の治療薬として用いられるのはどれか。",
         choices=[{"key": "A", "text": "抗コリン薬"}, {"key": "B", "text": "βラクタム系抗菌薬"}, {"key": "C", "text": "ACE阻害薬"}, {"key": "D", "text": "スタチン"}],
         correct_choice_key="A",
         explanation="過活動膀胱には膀胱平滑筋の過収縮を抑制する抗コリン薬やβ3作動薬が用いられる。"),
    dict(category="泌尿器", exam_type="KOKUSHI", difficulty=2,
         question_text="腎細胞癌の三徴に含まれないのはどれか。",
         choices=[{"key": "A", "text": "血尿"}, {"key": "B", "text": "側腹部痛"}, {"key": "C", "text": "腹部腫瘤"}, {"key": "D", "text": "関節痛"}],
         correct_choice_key="D",
         explanation="腎細胞癌の古典的三徴は血尿・側腹部痛・腹部腫瘤であり、関節痛は含まれない。"),

    # 眼科
    dict(category="眼科", exam_type="CBT", difficulty=1,
         question_text="眼圧上昇を特徴とし視神経障害をきたす疾患はどれか。",
         choices=[{"key": "A", "text": "白内障"}, {"key": "B", "text": "緑内障"}, {"key": "C", "text": "結膜炎"}, {"key": "D", "text": "麦粒腫"}],
         correct_choice_key="B",
         explanation="緑内障は眼圧上昇等を背景とした視神経障害により視野障害をきたす疾患である。"),
    dict(category="眼科", exam_type="CBT", difficulty=1,
         question_text="加齢に伴う水晶体の混濁により視力低下をきたす疾患はどれか。",
         choices=[{"key": "A", "text": "白内障"}, {"key": "B", "text": "網膜剥離"}, {"key": "C", "text": "角膜炎"}, {"key": "D", "text": "霰粒腫"}],
         correct_choice_key="A",
         explanation="白内障は水晶体の混濁により羞明や視力低下をきたす加齢性変化の代表疾患である。"),
    dict(category="眼科", exam_type="CBT", difficulty=2,
         question_text="糖尿病網膜症の進行に関与する主な機序はどれか。",
         choices=[{"key": "A", "text": "網膜血管の透過性亢進と新生血管形成"}, {"key": "B", "text": "水晶体の弾性低下"}, {"key": "C", "text": "角膜の菲薄化"}, {"key": "D", "text": "涙液分泌の低下"}],
         correct_choice_key="A",
         explanation="糖尿病網膜症は慢性高血糖による網膜細小血管障害を背景に血管透過性亢進と新生血管形成が進行し、失明の原因となりうる。"),
    dict(category="眼科", exam_type="KOKUSHI", difficulty=3,
         question_text="急性緑内障発作の典型的症状はどれか。",
         choices=[{"key": "A", "text": "無痛性の視野欠損のみ"}, {"key": "B", "text": "激しい眼痛・頭痛・嘔気を伴う急激な視力低下"}, {"key": "C", "text": "持続する眼脂"}, {"key": "D", "text": "羞明のみ"}],
         correct_choice_key="B",
         explanation="急性緑内障発作は眼圧の急上昇により激しい眼痛・頭痛・嘔気・急激な視力低下をきたす眼科救急疾患である。"),
    dict(category="眼科", exam_type="KOKUSHI", difficulty=3,
         question_text="網膜剥離の前駆症状として特徴的なのはどれか。",
         choices=[{"key": "A", "text": "光視症・飛蚊症の増加"}, {"key": "B", "text": "眼瞼の腫脹"}, {"key": "C", "text": "結膜充血のみ"}, {"key": "D", "text": "複視のみ"}],
         correct_choice_key="A",
         explanation="網膜剥離では硝子体牽引による光視症や飛蚊症の急激な増加が前駆症状として現れることが多い。"),

    # 耳鼻咽喉科
    dict(category="耳鼻咽喉科", exam_type="CBT", difficulty=2,
         question_text="感音難聴の原因となる病変部位はどれか。",
         choices=[{"key": "A", "text": "外耳道"}, {"key": "B", "text": "鼓膜"}, {"key": "C", "text": "内耳・聴神経"}, {"key": "D", "text": "中耳耳小骨"}],
         correct_choice_key="C",
         explanation="感音難聴は内耳(蝸牛)や聴神経の障害により生じ、伝音難聴(外耳・中耳の障害)と区別される。"),
    dict(category="耳鼻咽喉科", exam_type="CBT", difficulty=2,
         question_text="メニエール病の三徴に含まれるのはどれか。",
         choices=[{"key": "A", "text": "回転性めまい・耳鳴・難聴"}, {"key": "B", "text": "発熱・咽頭痛・咳嗽"}, {"key": "C", "text": "鼻閉・鼻漏・くしゃみ"}, {"key": "D", "text": "嗄声・嚥下障害・体重減少"}],
         correct_choice_key="A",
         explanation="メニエール病は内リンパ水腫を背景に反復する回転性めまい、耳鳴、難聴を三徴とする。"),
    dict(category="耳鼻咽喉科", exam_type="KOKUSHI", difficulty=3,
         question_text="急性喉頭蓋炎で最も注意すべき合併症はどれか。",
         choices=[{"key": "A", "text": "気道閉塞"}, {"key": "B", "text": "難聴"}, {"key": "C", "text": "めまい"}, {"key": "D", "text": "嗅覚障害"}],
         correct_choice_key="A",
         explanation="急性喉頭蓋炎は急速に進行する気道閉塞をきたしうる耳鼻咽喉科救急疾患である。"),
    dict(category="耳鼻咽喉科", exam_type="CBT", difficulty=1,
         question_text="アレルギー性鼻炎の三主徴に含まれないのはどれか。",
         choices=[{"key": "A", "text": "発作性反復性のくしゃみ"}, {"key": "B", "text": "水様性鼻漏"}, {"key": "C", "text": "鼻閉"}, {"key": "D", "text": "嗄声"}],
         correct_choice_key="D",
         explanation="アレルギー性鼻炎の三主徴はくしゃみ・水様性鼻漏・鼻閉であり、嗄声は含まれない。"),
    dict(category="耳鼻咽喉科", exam_type="KOKUSHI", difficulty=3,
         question_text="扁桃周囲膿瘍の特徴的な所見はどれか。",
         choices=[{"key": "A", "text": "開口障害と患側口蓋垂の健側偏位"}, {"key": "B", "text": "両側対称性の腫脹のみ"}, {"key": "C", "text": "無痛性の頸部腫瘤"}, {"key": "D", "text": "聴力低下"}],
         correct_choice_key="A",
         explanation="扁桃周囲膿瘍は著明な咽頭痛・開口障害(トリスムス)、患側扁桃の腫脹と口蓋垂の健側偏位を特徴とする。"),

    # 皮膚
    dict(category="皮膚", exam_type="CBT", difficulty=2,
         question_text="アトピー性皮膚炎の皮膚バリア機能異常に関連する遺伝子はどれか。",
         choices=[{"key": "A", "text": "フィラグリン遺伝子"}, {"key": "B", "text": "BRCA1遺伝子"}, {"key": "C", "text": "ジストロフィン遺伝子"}, {"key": "D", "text": "HTT遺伝子"}],
         correct_choice_key="A",
         explanation="フィラグリン遺伝子の変異は皮膚バリア機能低下を介しアトピー性皮膚炎の発症・増悪に関与するとされる。"),
    dict(category="皮膚", exam_type="CBT", difficulty=1,
         question_text="帯状疱疹の原因ウイルスはどれか。",
         choices=[{"key": "A", "text": "単純ヘルペスウイルス"}, {"key": "B", "text": "水痘・帯状疱疹ウイルス"}, {"key": "C", "text": "EBウイルス"}, {"key": "D", "text": "ヒトパピローマウイルス"}],
         correct_choice_key="B",
         explanation="帯状疱疹は水痘罹患後に神経節に潜伏していた水痘・帯状疱疹ウイルスの再活性化により生じる。"),
    dict(category="皮膚", exam_type="CBT", difficulty=1,
         question_text="蕁麻疹の病態に中心的に関与する細胞はどれか。",
         choices=[{"key": "A", "text": "好中球"}, {"key": "B", "text": "肥満細胞"}, {"key": "C", "text": "破骨細胞"}, {"key": "D", "text": "赤芽球"}],
         correct_choice_key="B",
         explanation="蕁麻疹は肥満細胞からのヒスタミン等の化学伝達物質遊離により膨疹と掻痒を生じる。"),
    dict(category="皮膚", exam_type="KOKUSHI", difficulty=3,
         question_text="基底細胞癌の特徴として適切なのはどれか。",
         choices=[{"key": "A", "text": "転移は稀で局所浸潤性に進行する"}, {"key": "B", "text": "極めて転移しやすい"}, {"key": "C", "text": "若年者に好発する"}, {"key": "D", "text": "紫外線曝露と無関係"}],
         correct_choice_key="A",
         explanation="基底細胞癌は日光曝露部に好発する皮膚悪性腫瘍で、転移は稀だが局所浸潤性に進行しうる。"),
    dict(category="皮膚", exam_type="KOKUSHI", difficulty=2,
         question_text="乾癬に特徴的な皮膚所見はどれか。",
         choices=[{"key": "A", "text": "銀白色の鱗屑を伴う紅斑局面"}, {"key": "B", "text": "水疱形成のみ"}, {"key": "C", "text": "色素脱失斑"}, {"key": "D", "text": "蜘蛛状血管腫"}],
         correct_choice_key="A",
         explanation="乾癬は境界明瞭な紅斑局面上に銀白色の鱗屑を伴う慢性炎症性皮膚疾患である。"),

    # 精神
    dict(category="精神", exam_type="CBT", difficulty=2,
         question_text="統合失調症の陽性症状に含まれるのはどれか。",
         choices=[{"key": "A", "text": "幻覚・妄想"}, {"key": "B", "text": "感情の平板化"}, {"key": "C", "text": "意欲の低下"}, {"key": "D", "text": "社会的引きこもり"}],
         correct_choice_key="A",
         explanation="統合失調症の陽性症状は幻覚・妄想など通常みられない症状の出現であり、陰性症状(感情鈍麻・意欲低下等)と区別される。"),
    dict(category="精神", exam_type="CBT", difficulty=1,
         question_text="うつ病の診断において中核的な症状はどれか。",
         choices=[{"key": "A", "text": "抑うつ気分と興味・喜びの喪失"}, {"key": "B", "text": "多幸感の持続"}, {"key": "C", "text": "過活動"}, {"key": "D", "text": "食思の著明な亢進のみ"}],
         correct_choice_key="A",
         explanation="うつ病の中核症状は持続する抑うつ気分と興味・喜びの喪失(アンヘドニア)である。"),
    dict(category="精神", exam_type="CBT", difficulty=2,
         question_text="パニック障害の特徴的症状はどれか。",
         choices=[{"key": "A", "text": "突然生じる強い恐怖感と動悸・呼吸困難などの身体症状"}, {"key": "B", "text": "緩徐に進行する記憶障害"}, {"key": "C", "text": "持続する幻聴"}, {"key": "D", "text": "慢性の運動チック"}],
         correct_choice_key="A",
         explanation="パニック障害は誘因なく突然出現する強い恐怖感とともに動悸・発汗・呼吸困難などの身体症状(パニック発作)を特徴とする。"),
    dict(category="精神", exam_type="KOKUSHI", difficulty=2,
         question_text="双極性障害の躁状態でみられる症状はどれか。",
         choices=[{"key": "A", "text": "睡眠欲求の減少と気分高揚"}, {"key": "B", "text": "意欲低下と自責感"}, {"key": "C", "text": "持続する不安のみ"}, {"key": "D", "text": "記憶障害の進行"}],
         correct_choice_key="A",
         explanation="躁状態では睡眠欲求の減少、気分高揚、多弁、行動の亢進などがみられる。"),
    dict(category="精神", exam_type="KOKUSHI", difficulty=3,
         question_text="アルコール離脱症候群でみられる症状はどれか。",
         choices=[{"key": "A", "text": "振戦・発汗・不眠などの自律神経症状"}, {"key": "B", "text": "著明な徐脈のみ"}, {"key": "C", "text": "食欲亢進"}, {"key": "D", "text": "体温低下"}],
         correct_choice_key="A",
         explanation="アルコール離脱症候群では振戦・発汗・不眠・不安などの自律神経症状が出現し、重症例では振戦せん妄に至ることもある。"),

    # 整形
    dict(category="整形", exam_type="CBT", difficulty=1,
         question_text="骨折の治癒過程における初期段階として正しいのはどれか。",
         choices=[{"key": "A", "text": "血腫形成"}, {"key": "B", "text": "リモデリング"}, {"key": "C", "text": "骨性仮骨形成"}, {"key": "D", "text": "軟骨性仮骨形成"}],
         correct_choice_key="A",
         explanation="骨折治癒はまず骨折部の血腫形成から始まり、その後炎症反応、仮骨形成、リモデリングへと進行する。"),
    dict(category="整形", exam_type="CBT", difficulty=1,
         question_text="変形性膝関節症の主な病態はどれか。",
         choices=[{"key": "A", "text": "関節軟骨の変性・摩耗"}, {"key": "B", "text": "関節リウマチと同一の自己免疫機序"}, {"key": "C", "text": "化膿性炎症"}, {"key": "D", "text": "骨腫瘍性変化"}],
         correct_choice_key="A",
         explanation="変形性膝関節症は加齢や荷重負荷による関節軟骨の変性・摩耗を主病態とする非炎症性の関節疾患である。"),
    dict(category="整形", exam_type="CBT", difficulty=2,
         question_text="関節リウマチに特徴的な自己抗体はどれか。",
         choices=[{"key": "A", "text": "リウマトイド因子・抗CCP抗体"}, {"key": "B", "text": "抗核抗体のみ"}, {"key": "C", "text": "抗Jo-1抗体"}, {"key": "D", "text": "抗セントロメア抗体"}],
         correct_choice_key="A",
         explanation="関節リウマチではリウマトイド因子や抗CCP抗体が診断・重症度評価に有用な自己抗体として知られる。"),
    dict(category="整形", exam_type="KOKUSHI", difficulty=2,
         question_text="骨粗鬆症の診断・評価に用いられる代表的検査はどれか。",
         choices=[{"key": "A", "text": "骨密度測定(DXA法)"}, {"key": "B", "text": "関節造影"}, {"key": "C", "text": "筋電図"}, {"key": "D", "text": "神経伝導検査"}],
         correct_choice_key="A",
         explanation="骨粗鬆症の診断にはDXA法による骨密度測定が標準的に用いられる。"),
    dict(category="整形", exam_type="KOKUSHI", difficulty=3,
         question_text="腰椎椎間板ヘルニアで坐骨神経痛を生じる主な機序はどれか。",
         choices=[{"key": "A", "text": "脱出した髄核による神経根圧迫"}, {"key": "B", "text": "筋肉の過剰収縮のみ"}, {"key": "C", "text": "骨膜の炎症のみ"}, {"key": "D", "text": "靭帯の肥厚のみ"}],
         correct_choice_key="A",
         explanation="腰椎椎間板ヘルニアは脱出した髄核が神経根を圧迫することで坐骨神経痛などの神経症状を生じる。"),

    # 麻酔
    dict(category="麻酔", exam_type="CBT", difficulty=1,
         question_text="全身麻酔の三要素に含まれないのはどれか。",
         choices=[{"key": "A", "text": "鎮静(意識消失)"}, {"key": "B", "text": "鎮痛"}, {"key": "C", "text": "筋弛緩"}, {"key": "D", "text": "解熱"}],
         correct_choice_key="D",
         explanation="全身麻酔の三要素は鎮静(意識消失)・鎮痛・筋弛緩であり、解熱は含まれない。"),
    dict(category="麻酔", exam_type="CBT", difficulty=2,
         question_text="局所麻酔薬の作用機序はどれか。",
         choices=[{"key": "A", "text": "電位依存性ナトリウムチャネルの遮断"}, {"key": "B", "text": "GABA受容体の増強"}, {"key": "C", "text": "アセチルコリン受容体の遮断"}, {"key": "D", "text": "カリウムチャネルの開口"}],
         correct_choice_key="A",
         explanation="局所麻酔薬は神経細胞膜の電位依存性ナトリウムチャネルを遮断し、活動電位の伝播を抑制する。"),
    dict(category="麻酔", exam_type="KOKUSHI", difficulty=3,
         question_text="悪性高熱症の誘因となる代表的な麻酔薬・筋弛緩薬はどれか。",
         choices=[{"key": "A", "text": "吸入麻酔薬とスキサメトニウム"}, {"key": "B", "text": "プロポフォール"}, {"key": "C", "text": "フェンタニル"}, {"key": "D", "text": "局所麻酔薬単独"}],
         correct_choice_key="A",
         explanation="悪性高熱症は揮発性吸入麻酔薬やスキサメトニウム投与を契機に骨格筋の異常な代謝亢進をきたす致死的合併症である。"),
    dict(category="麻酔", exam_type="CBT", difficulty=2,
         question_text="気管挿管前の評価に用いられる、開口時の口腔内視認度分類はどれか。",
         choices=[{"key": "A", "text": "Mallampati分類"}, {"key": "B", "text": "ASA分類"}, {"key": "C", "text": "NYHA分類"}, {"key": "D", "text": "Child-Pugh分類"}],
         correct_choice_key="A",
         explanation="Mallampati分類は開口時の咽頭構造の視認度から挿管困難の予測に用いられる評価法である。"),
    dict(category="麻酔", exam_type="KOKUSHI", difficulty=2,
         question_text="硬膜外麻酔と比較した脊椎くも膜下麻酔(脊麻)の特徴はどれか。",
         choices=[{"key": "A", "text": "効果発現が速く単回投与が主体"}, {"key": "B", "text": "効果発現が遅い"}, {"key": "C", "text": "カテーテル留置による持続投与が標準"}, {"key": "D", "text": "局所麻酔薬を使用しない"}],
         correct_choice_key="A",
         explanation="脊椎くも膜下麻酔はくも膜下腔に直接局所麻酔薬を投与するため効果発現が速く、単回投与が主体となることが多い。"),

    # 放射線
    dict(category="放射線", exam_type="CBT", difficulty=1,
         question_text="単純X線写真において、カルシウムを多く含む骨のように吸収の大きい組織の見え方はどれか。",
         choices=[{"key": "A", "text": "白く(高吸収)描出される"}, {"key": "B", "text": "黒く(低吸収)描出される"}, {"key": "C", "text": "描出されない"}, {"key": "D", "text": "必ず造影が必要"}],
         correct_choice_key="A",
         explanation="X線の吸収が大きい骨組織は写真上白く(高吸収)描出される。"),
    dict(category="放射線", exam_type="CBT", difficulty=2,
         question_text="放射線被曝による確定的影響の特徴はどれか。",
         choices=[{"key": "A", "text": "しきい値が存在し線量依存性に重症度が増す"}, {"key": "B", "text": "しきい値がなく線量に比例して発生確率が増す"}, {"key": "C", "text": "遺伝しない影響のみを指す"}, {"key": "D", "text": "必ず致死的である"}],
         correct_choice_key="A",
         explanation="確定的影響(組織反応)はしきい線量が存在し、被曝線量が増えるほど重症度が増す点が確率的影響と異なる。"),
    dict(category="放射線", exam_type="CBT", difficulty=1,
         question_text="CT検査とMRI検査の比較として適切なのはどれか。",
         choices=[{"key": "A", "text": "CTは電離放射線を用い、MRIは磁場と電波を用いる"}, {"key": "B", "text": "MRIは電離放射線を用いる"}, {"key": "C", "text": "CTは磁場を用いる"}, {"key": "D", "text": "両者とも放射線被曝はない"}],
         correct_choice_key="A",
         explanation="CTはX線(電離放射線)を用いるのに対し、MRIは強力な磁場とラジオ波を利用し電離放射線被曝を伴わない。"),
    dict(category="放射線", exam_type="KOKUSHI", difficulty=2,
         question_text="妊婦への画像検査で優先的に避けるべきなのはどれか。",
         choices=[{"key": "A", "text": "腹部超音波検査"}, {"key": "B", "text": "不要不急のX線・CT検査"}, {"key": "C", "text": "MRI検査全般"}, {"key": "D", "text": "血液検査"}],
         correct_choice_key="B",
         explanation="妊婦では胎児被曝の観点から不要不急のX線・CT検査は避け、必要時は超音波やMRIが優先的に検討される。"),
    dict(category="放射線", exam_type="KOKUSHI", difficulty=3,
         question_text="ヨード造影剤アレルギーの既往がある患者への対応として適切なのはどれか。",
         choices=[{"key": "A", "text": "前投薬や代替検査を検討し慎重に判断する"}, {"key": "B", "text": "既往の有無にかかわらず通常通り使用する"}, {"key": "C", "text": "必ず倍量投与する"}, {"key": "D", "text": "経口摂取のみで代用する"}],
         correct_choice_key="A",
         explanation="造影剤アレルギー既往がある場合は前投薬(ステロイド・抗ヒスタミン薬)の実施や代替検査の検討など慎重な対応が必要である。"),

    # 多選択肢 (multiple-condition combination questions; single-best-answer format)
    dict(category="多選択肢", exam_type="CBT", difficulty=2,
         question_text="糖尿病の診断に用いられる検査項目の組み合わせとして適切なのはどれか。",
         choices=[{"key": "A", "text": "空腹時血糖・HbA1c・75gOGTT"}, {"key": "B", "text": "血沈のみ"}, {"key": "C", "text": "心電図のみ"}, {"key": "D", "text": "胸部X線のみ"}],
         correct_choice_key="A",
         explanation="糖尿病の診断には空腹時血糖、随時血糖、75gOGTT、HbA1cが用いられ、複数の基準を組み合わせて総合的に判定する。"),
    dict(category="多選択肢", exam_type="CBT", difficulty=2,
         question_text="メタボリックシンドロームの診断項目に含まれる組み合わせとして適切なのはどれか。",
         choices=[{"key": "A", "text": "内臓脂肪蓄積・血圧高値・脂質異常・高血糖"}, {"key": "B", "text": "視力低下・聴力低下"}, {"key": "C", "text": "骨密度低下のみ"}, {"key": "D", "text": "貧血のみ"}],
         correct_choice_key="A",
         explanation="メタボリックシンドロームは内臓脂肪蓄積を基盤に血圧高値・脂質異常・高血糖のうち2項目以上を満たす場合に診断される。"),
    dict(category="多選択肢", exam_type="KOKUSHI", difficulty=3,
         question_text="急性心筋梗塞の診断に用いる情報の組み合わせとして適切なのはどれか。",
         choices=[{"key": "A", "text": "心電図変化・心筋逸脱酵素・臨床症状"}, {"key": "B", "text": "聴力検査のみ"}, {"key": "C", "text": "視野検査のみ"}, {"key": "D", "text": "骨シンチグラフィのみ"}],
         correct_choice_key="A",
         explanation="急性心筋梗塞の診断は典型的な胸部症状、心電図変化(ST上昇等)、トロポニン等の心筋逸脱酵素上昇を総合して行う。"),
    dict(category="多選択肢", exam_type="CBT", difficulty=2,
         question_text="慢性閉塞性肺疾患(COPD)の管理として適切な組み合わせはどれか。",
         choices=[{"key": "A", "text": "禁煙指導・気管支拡張薬・呼吸リハビリテーション"}, {"key": "B", "text": "高脂肪食の推奨のみ"}, {"key": "C", "text": "絶対安静のみ"}, {"key": "D", "text": "抗凝固薬単独"}],
         correct_choice_key="A",
         explanation="COPDの管理は禁煙が最重要であり、気管支拡張薬による症状緩和、呼吸リハビリテーションを組み合わせて行う。"),
    dict(category="多選択肢", exam_type="KOKUSHI", difficulty=2,
         question_text="脳卒中の危険因子として適切な組み合わせはどれか。",
         choices=[{"key": "A", "text": "高血圧・心房細動・糖尿病・喫煙"}, {"key": "B", "text": "低血圧のみ"}, {"key": "C", "text": "若年であること"}, {"key": "D", "text": "運動習慣"}],
         correct_choice_key="A",
         explanation="脳卒中の主な危険因子には高血圧、心房細動、糖尿病、脂質異常症、喫煙などが挙げられる。"),

    # 四連問 (linked case-vignette series; single-best-answer format)
    dict(category="四連問", exam_type="KOKUSHI", difficulty=2,
         question_text="65歳男性。労作時の胸痛を主訴に受診した。安静により症状は軽快した。まず疑うべき疾患はどれか。",
         choices=[{"key": "A", "text": "労作性狭心症"}, {"key": "B", "text": "気胸"}, {"key": "C", "text": "逆流性食道炎"}, {"key": "D", "text": "肋間神経痛"}],
         correct_choice_key="A",
         explanation="労作により誘発され安静で軽快する胸痛は労作性狭心症に典型的であり、まず疑うべき疾患である。"),
    dict(category="四連問", exam_type="KOKUSHI", difficulty=2,
         question_text="上記の患者(65歳男性、労作性狭心症疑い)の精査として最も優先すべき検査はどれか。",
         choices=[{"key": "A", "text": "心電図・心エコー・負荷心電図など虚血評価"}, {"key": "B", "text": "腹部エコーのみ"}, {"key": "C", "text": "頭部MRIのみ"}, {"key": "D", "text": "聴力検査"}],
         correct_choice_key="A",
         explanation="狭心症が疑われる場合、心電図・心エコー・負荷試験など虚血評価を優先して行う。"),
    dict(category="四連問", exam_type="KOKUSHI", difficulty=3,
         question_text="同患者の冠動脈造影で有意狭窄を認めた場合の治療選択として適切なのはどれか。",
         choices=[{"key": "A", "text": "経皮的冠動脈インターベンション(PCI)またはバイパス手術の検討"}, {"key": "B", "text": "経過観察のみで治療介入は不要"}, {"key": "C", "text": "抗菌薬投与のみ"}, {"key": "D", "text": "ステロイド投与のみ"}],
         correct_choice_key="A",
         explanation="有意狭窄を認める冠動脈疾患ではPCIや冠動脈バイパス術(CABG)などの血行再建術が検討される。"),
    dict(category="四連問", exam_type="KOKUSHI", difficulty=2,
         question_text="同患者に対する二次予防として重要な生活指導はどれか。",
         choices=[{"key": "A", "text": "禁煙・脂質管理・血圧管理・適度な運動"}, {"key": "B", "text": "絶対安静の継続"}, {"key": "C", "text": "高脂肪食の推奨"}, {"key": "D", "text": "運動制限のみで薬物療法は不要"}],
         correct_choice_key="A",
         explanation="虚血性心疾患の二次予防には禁煙、脂質・血圧管理、適度な運動療法、抗血小板薬などの包括的介入が重要である。"),
    dict(category="四連問", exam_type="KOKUSHI", difficulty=3,
         question_text="同患者が治療後に突然の意識消失と心停止をきたした場合、まず行うべき対応はどれか。",
         choices=[{"key": "A", "text": "胸骨圧迫を中心とした心肺蘇生とAEDの使用"}, {"key": "B", "text": "経過観察"}, {"key": "C", "text": "内服薬の追加のみ"}, {"key": "D", "text": "家族への説明を最優先する"}],
         correct_choice_key="A",
         explanation="心停止を確認した場合はただちに胸骨圧迫を中心とした心肺蘇生を開始し、AEDによる除細動を試みることが最優先される。"),
]


class Command(BaseCommand):
    help = "Seed sample Question data for the remaining category-list categories."

    def handle(self, *args, **options):
        created_count = 0
        for q in EXTRA_QUESTIONS:
            _, was_created = Question.objects.get_or_create(
                category=q["category"],
                exam_type=q["exam_type"],
                explanation=q["explanation"],
                defaults=dict(
                    difficulty=q["difficulty"],
                    question_text=q["question_text"],
                    choices=q["choices"],
                    correct_choice_key=q["correct_choice_key"],
                    visibility=Question.Visibility.PUBLIC,
                ),
            )
            created_count += int(was_created)

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created_count} new questions across extra categories "
                f"(total in DB: {Question.objects.count()})."
            )
        )
