# Generated by Django 6.0.7 on 2026-07-14 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '模試',
                'verbose_name_plural': '模試',
            },
        ),
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_questions', to='exams.mockexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'verbose_name': '模試設問',
                'verbose_name_plural': '模試設問',
                'ordering': ['order'],
                'unique_together': {('mock_exam', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '模試結果',
                'verbose_name_plural': '模試結果',
                'unique_together': {('user', 'mock_exam')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='月初日で保持 (例: 2026-07-01)')),
                ('questions_solved', models.PositiveIntegerField(default=0)),
                ('correct_rate', models.FloatField(blank=True, help_text='questions_solved >= 1000のユーザーのみ算出', null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rankings', to='accounts.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '月間ランキング',
                'verbose_name_plural': '月間ランキング',
                'unique_together': {('user', 'month')},
            },
        ),
    ]
