# Generated by Django 6.0.7 on 2026-07-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
        ("exams", "0002_retarget_user_fks_to_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyranking",
            name="correct_rate",
            field=models.FloatField(
                blank=True,
                help_text="questions_solved >= exams.constants.MIN_QUESTIONS_FOR_ACCURACY_RANKING (=100) のユーザーのみ算出",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "全国（個人）"),
                            ("university", "学内（個人）"),
                            ("university_aggregate", "大学別（大学単位）"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(help_text='"all" または "YYYY-MM"', max_length=7),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("solved", "解いた問題数"), ("accuracy", "正答率")],
                        max_length=10,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "value",
                    models.FloatField(
                        help_text="solved=ユニーク問題数 / accuracy=初回解答の正答率(%)"
                    ),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="個人行=ユニーク解答問題数 / 大学行=対象メンバー数",
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_snapshots",
                        to="accounts.profile",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        help_text="scope=university のとき、どの大学の学内ランキングか",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_snapshots",
                        to="accounts.university",
                    ),
                ),
                (
                    "university_target",
                    models.ForeignKey(
                        blank=True,
                        help_text="scope=university_aggregate のとき、順位づけされた大学",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranked_snapshots",
                        to="accounts.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "ランキングスナップショット",
                "verbose_name_plural": "ランキングスナップショット",
                "indexes": [
                    models.Index(
                        fields=["scope", "period", "metric", "rank"],
                        name="exams_ranki_scope_d54414_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "scope",
                            "university",
                            "period",
                            "metric",
                            "profile",
                            "university_target",
                        ),
                        name="uniq_ranking_snapshot_entry",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
