# Generated by Django 6.0.7 on 2026-07-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_monthlyranking_correct_rate_rankingsnapshot"),
        ("quiz", "0006_answerhistory_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexam",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="question_count",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "予定"),
                    ("open", "受験可"),
                    ("closed", "終了"),
                    ("graded", "採点済"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="target_grade_max",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="target_grade_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="deviation_score",
            field=models.FloatField(blank=True, help_text="偏差値", null=True),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="section_scores",
            field=models.JSONField(
                blank=True, default=dict, help_text='{"D-5": 0.72, "D-7": 0.55, ...}'
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="university_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mockresult",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="MockAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_choice_key",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "mock_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.mockresult",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "模試解答",
                "verbose_name_plural": "模試解答",
                "unique_together": {("mock_result", "question")},
            },
        ),
    ]
