# Generated by Django 6.0.7 on 2026-07-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_mockexam_duration_minutes_mockexam_question_count_and_more"),
        ("quiz", "0007_reviewreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexam",
            name="exam_type",
            field=models.CharField(
                choices=[("CBT", "CBT"), ("KOKUSHI", "医師国家試験")],
                default="CBT",
                help_text="出題する問題プール（Question.exam_type）と対象学年の表示振り分けに使う",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="kind",
            field=models.CharField(
                choices=[
                    ("weekly", "週次小テスト"),
                    ("monthly", "月次模試"),
                    ("large", "大型模試（国試直前）"),
                    ("cbt_once", "CBT模試（生涯1回）"),
                ],
                default="monthly",
                help_text="週次/月次はポイントが増減する。大型/CBTは対象学年を絞った参考成績のみ",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="irt_scaled_score",
            field=models.FloatField(
                blank=True,
                help_text="CBT模試のみ: 50+10θ の偏差値相当スケール",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="irt_theta",
            field=models.FloatField(
                blank=True, help_text="CBT模試のみ: IRT能力値θ(MAP推定)", null=True
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="points_delta",
            field=models.IntegerField(
                blank=True,
                help_text="週次/月次のみ: この回で増減した対戦・模試合算ポイント",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="score_distribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='大型模試のみ算出: {"bucket_size":.., "buckets":[..], "my_bucket":i}',
            ),
        ),
        migrations.AddField(
            model_name="mockresult",
            name="section_deviation_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='大型模試のみ算出: {"D-5": 62.1, ...}（分野別の偏差値）',
            ),
        ),
        migrations.CreateModel(
            name="ItemParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.FloatField(default=1.0, help_text="識別力パラメータ")),
                ("b", models.FloatField(default=0.0, help_text="困難度パラメータ")),
                (
                    "calibrated_n",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="較正に使った解答数（少ないと初期値のまま）",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irt_param",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "IRT項目パラメータ",
                "verbose_name_plural": "IRT項目パラメータ",
            },
        ),
    ]
