# Generated by Django 6.0.7 on 2026-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_mockexam_exam_type_mockexam_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockexam",
            name="kind",
            field=models.CharField(
                choices=[
                    ("monthly", "月次実力テスト"),
                    ("large", "国試模試（国試2ヶ月前）"),
                    ("cbt_once", "CBT模試（生涯1回）"),
                ],
                default="monthly",
                help_text="月次はポイントが増減する。国試模試/CBT模試は対象学年を絞った参考成績のみ",
                max_length=20,
            ),
        ),
    ]
