# Generated by Django 6.0.7 on 2026-07-14 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(choices=[(1, '易'), (2, '標準'), (3, '難')], default=2)),
                ('exam_type', models.CharField(choices=[('CBT', 'CBT'), ('KOKUSHI', '医師国家試験')], max_length=10)),
                ('choices', models.JSONField(help_text='[{"key": "A", "text": "..."}, ...]')),
                ('correct_choice_key', models.CharField(max_length=4)),
                ('explanation', models.TextField()),
                ('visibility', models.CharField(choices=[('public', '公開（全ユーザー）'), ('university_only', '学内限定')], default='public', max_length=20)),
                ('correct_rate', models.FloatField(default=0.0, help_text='バッチ集計される全体正答率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, help_text='nullの場合は公式問題', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, help_text='visibility=university_onlyの場合の閲覧範囲', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='accounts.university')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
        migrations.CreateModel(
            name='AnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('double_circle', '◎'), ('circle', '○'), ('triangle', '△'), ('cross', '✕'), ('unstudied', '未演習')], default='unstudied', max_length=20)),
                ('correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='quiz.question')),
            ],
            options={
                'verbose_name': '解答履歴',
                'verbose_name_plural': '解答履歴',
                'indexes': [models.Index(fields=['user', 'question'], name='quiz_answer_user_id_0bc7b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_at', models.DateTimeField()),
                ('interval_days', models.FloatField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '復習スケジュール',
                'verbose_name_plural': '復習スケジュール',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
