# Generated by Django 6.0.7 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, help_text='設問文（症例文など）'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='カテゴリ内のサブトピック（疾患名など、任意）', max_length=100),
        ),
    ]
