# Hand-written (not autogenerated): retargets user FKs from accounts.User
# (bigint PK) to accounts.Profile (UUID PK). Postgres cannot ALTER a bigint
# column to uuid (no cast exists), so the columns are dropped and re-added
# instead of AlterField. Tables are expected to be empty at this point —
# there is no production data (spec §9-1); dev databases are rebuilt (see
# README「データベースの作り直し」).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
        ("quiz", "0002_question_question_text_question_topic"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="answerhistory",
            name="quiz_answer_user_id_0bc7b3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="reviewschedule",
            unique_together=set(),
        ),
        migrations.RemoveField(model_name="question", name="creator"),
        migrations.RemoveField(model_name="answerhistory", name="user"),
        migrations.RemoveField(model_name="reviewschedule", name="user"),
        migrations.AddField(
            model_name="question",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="nullの場合は公式問題",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="answerhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_histories",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewschedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_schedules",
                to="accounts.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="answerhistory",
            index=models.Index(
                fields=["user", "question"], name="quiz_answer_user_id_0bc7b3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewschedule",
            unique_together={("user", "question")},
        ),
    ]
