# Generated by Django 6.0.7 on 2026-07-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
        ("quiz", "0003_retarget_user_fks_to_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBTBlueprint",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text='例 "D-5-4)-(2)-③"',
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section", models.CharField(help_text="大区分 A〜F", max_length=2)),
                (
                    "area",
                    models.CharField(db_index=True, help_text='例 "D-5"', max_length=8),
                ),
                (
                    "area_title",
                    models.CharField(help_text='例 "循環器系"', max_length=100),
                ),
                ("subsection_title", models.CharField(blank=True, max_length=255)),
                (
                    "objective_text",
                    models.TextField(
                        blank=True,
                        help_text="到達目標の原文。生成プロンプト専用・API非公開",
                    ),
                ),
                (
                    "depth",
                    models.CharField(
                        blank=True,
                        help_text="説明できる / 概説できる / 列挙できる",
                        max_length=20,
                    ),
                ),
                (
                    "class_group",
                    models.CharField(
                        blank=True, choices=[("I", "Ⅰ群"), ("II", "Ⅱ群")], max_length=2
                    ),
                ),
                ("disease_names", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "CBT出題基準",
                "verbose_name_plural": "CBT出題基準",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="answer_count",
            field=models.PositiveIntegerField(
                default=0, help_text="correct_rate の分母（解答時にインクリメント）"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="blueprint_code",
            field=models.CharField(
                blank=True, db_index=True, help_text='例 "D-5-4)-(2)-③"', max_length=32
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="class_group",
            field=models.CharField(
                blank=True, choices=[("I", "Ⅰ群"), ("II", "Ⅱ群")], max_length=2
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("M", "多選択肢択一"), ("Q", "順次解答四連問")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="医学的正確性レビュー者",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_questions",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="set_order",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="タイプQ内の1〜4", null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[
                    ("official", "公式"),
                    ("llm", "LLM生成"),
                    ("user", "ユーザー作成"),
                ],
                default="official",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "下書き"),
                    ("pending", "審査待ち"),
                    ("published", "公開"),
                    ("rejected", "却下"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_answer", "正解が誤っている"),
                            ("ambiguous", "設問が曖昧"),
                            ("typo", "誤字脱字"),
                            ("inappropriate", "不適切な内容"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="quiz.question",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_reports",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題通報",
                "verbose_name_plural": "問題通報",
            },
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "blueprint_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("case_stem", models.TextField(help_text="症例導入文")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("pending", "審査待ち"),
                            ("published", "公開"),
                            ("rejected", "却下"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("official", "公式"),
                            ("llm", "LLM生成"),
                            ("user", "ユーザー作成"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_sets",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "四連問セット",
                "verbose_name_plural": "四連問セット",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="question_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.questionset",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["status", "visibility", "category"],
                name="quiz_questi_status_2cb9ec_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionreport",
            unique_together={("question", "reporter")},
        ),
    ]
