# Generated by Django 6.0.7 on 2026-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
        ("quiz", "0004_cbtblueprint_question_answer_count_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answerhistory",
            index=models.Index(
                fields=["user", "answered_at"], name="quiz_answer_user_id_d66cbc_idx"
            ),
        ),
    ]
