# Generated by Django 6.0.7 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_answerhistory_quiz_answer_user_id_d66cbc_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerhistory",
            name="context",
            field=models.CharField(
                choices=[
                    ("solo", "ソロ"),
                    ("battle", "対戦"),
                    ("mock", "模試"),
                    ("review", "復習"),
                ],
                default="solo",
                max_length=10,
            ),
        ),
    ]
