# Generated by Django 6.0.7 on 2026-07-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notificationpreference_pushsubscription"),
        ("quiz", "0006_answerhistory_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("push", "Web Push"), ("email", "メール")],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("question_count", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reminders",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "復習リマインド",
                "verbose_name_plural": "復習リマインド",
                "indexes": [
                    models.Index(
                        fields=["profile", "scheduled_for"],
                        name="quiz_review_profile_7edb84_idx",
                    )
                ],
            },
        ),
    ]
