# Generated by Django 6.0.7 on 2026-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_strip_explanation_boilerplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_explanations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='選択肢ごとの解説 {"A": "…", "B": "…"}。空の選択肢は解説なし。',
            ),
        ),
    ]
