"""問題の報告に、選んだ理由をすべて持たせる。

報告の画面はチェックボックスで、問題文と解答の両方が間違っていることも
あるため1つに絞らない。既存の行は reason 1つぶんを入れておく。
"""

# Generated by Django 6.0.7 on 2026-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_strip_stray_column_separators"),
    ]

    def _fill_existing(apps, schema_editor):
        """すでにある報告は、単一の reason をそのまま一覧にする。"""
        QuestionReport = apps.get_model("quiz", "QuestionReport")
        for report in QuestionReport.objects.exclude(reason=""):
            QuestionReport.objects.filter(pk=report.pk).update(reasons=[report.reason])

    operations = [
        migrations.AddField(
            model_name="questionreport",
            name="reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="questionreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("wrong_question", "問題文が間違っている"),
                    ("wrong_answer", "解答が間違っている"),
                    ("ambiguous", "設問が曖昧"),
                    ("typo", "誤字脱字"),
                    ("inappropriate", "不適切な内容"),
                    ("other", "その他"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(_fill_existing, migrations.RunPython.noop),
    ]
