# Generated by Django 6.0.7 on 2026-09-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_deletedaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions_per_day", models.PositiveSmallIntegerField()),
                (
                    "effective_from",
                    models.DateField(
                        help_text="この日から適用する（Asia/Tokyo の日付）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_goals",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "1日の目標",
                "verbose_name_plural": "1日の目標",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "effective_from"),
                        name="habits_goal_one_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_on", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("daily", "今日の目標"),
                            ("streak", "連続記録"),
                            ("paused", "通知のお休み"),
                        ],
                        max_length=10,
                    ),
                ),
                ("template", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "学習リマインドの送信記録",
                "verbose_name_plural": "学習リマインドの送信記録",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "sent_on", "kind"),
                        name="habits_reminder_once_a_day",
                    )
                ],
            },
        ),
    ]
