# Generated by Django 6.0.7 on 2026-07-14 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', '参加者募集中'), ('in_progress', '対戦中'), ('finished', '終了')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_battle_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '対戦ルーム',
                'verbose_name_plural': '対戦ルーム',
            },
        ),
        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_answers', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='battle.battleroom')),
            ],
            options={
                'verbose_name': '対戦回答',
                'verbose_name_plural': '対戦回答',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battle.battleroom')),
            ],
            options={
                'verbose_name': '対戦参加者',
                'verbose_name_plural': '対戦参加者',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
