# Generated by Django 6.0.7 on 2026-07-23 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
        ("battle", "0002_retarget_user_fks_to_profile"),
        ("quiz", "0006_answerhistory_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="battleroom",
            name="category",
            field=models.CharField(
                blank=True, help_text="分野フィルタ（空なら全分野）", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="battleroom",
            name="question_count",
            field=models.PositiveSmallIntegerField(
                choices=[(5, "5問"), (10, "10問"), (20, "20問")], default=10
            ),
        ),
        migrations.CreateModel(
            name="BattleRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="battle.battleroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "対戦ラウンド",
                "verbose_name_plural": "対戦ラウンド",
                "ordering": ["round_number"],
                "unique_together": {("room", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="BattleBuzz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buzzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_choice_key",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_buzzes",
                        to="accounts.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buzzes",
                        to="battle.battleround",
                    ),
                ),
            ],
            options={
                "verbose_name": "早押し",
                "verbose_name_plural": "早押し",
            },
        ),
        migrations.DeleteModel(
            name="BattleAnswer",
        ),
        migrations.AddIndex(
            model_name="battlebuzz",
            index=models.Index(
                fields=["round", "buzzed_at"], name="battle_batt_round_i_fcc2ba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="battlebuzz",
            unique_together={("round", "profile")},
        ),
    ]
