# Generated by Django 6.0.7 on 2026-07-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_is_ai_profile_points_profile_ranked_matches"),
        ("battle", "0003_battleparticipant_last_seen_at_battleroom_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="points_delta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MatchmakingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_count", models.PositiveSmallIntegerField(default=10)),
                (
                    "tier_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="発行時点のランク（SS/S/A/B/C/D、未ランクは空）",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "対戦相手を探索中"),
                            ("matched", "マッチ成立（人間）"),
                            ("ai_matched", "マッチ成立（AI）"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="battle.battleroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchmaking_tickets",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "マッチメイキング待機",
                "verbose_name_plural": "マッチメイキング待機",
                "indexes": [
                    models.Index(
                        fields=["status", "question_count", "created_at"],
                        name="battle_matc_status_cba08a_idx",
                    )
                ],
            },
        ),
    ]
