# Generated by Django 6.0.7 on 2026-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0004_battleparticipant_points_delta_matchmakingticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="ai_tier",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="battleparticipant",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
