# Generated by Django 6.0.7 on 2026-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_battleparticipant_ai_tier_battleparticipant_left_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="hp",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="battleround",
            name="outcome",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
